### ISSUE TITLE
Stages data processing levels

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoflow#1]
There needs to be various stages or data processing levels for the flow. See https://github.com/uw-echospace/data-processing-levels/blob/main/discussion_2022-07-12.md for reference.

**Comment by lsetiawan** [comment]
Discussion of subpackages that will be used for each of the product levels can be found in PR https://github.com/OSOceanAcoustics/echopype/pull/817

**Comment by Sohambutala** [comment]
All flows are disjoint, can be written as standalone flows, and then merged into the prefect workflow. Closing this for now.
