### ISSUE TITLE
Echoflow Design

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#12]
I have started a Figma design to get more understanding of the flow of the functions and make validations more robust.

[Figma Prototype](https://www.figma.com/file/MMngyedbQclTo9DgV2eeJo/EchoFlow?type=whiteboard&t=fsQSIdY2AIh1lTm4-1)

**Comment by leewujung** [comment]
I recommend moving this to the Milestone "Code Refactoring" since they are the same sort of things, and refactoring requires a design.

**Comment by Sohambutala** [comment]
Closing this. The latest workflow figma can be found at [Figma Prototype](https://www.figma.com/file/MMngyedbQclTo9DgV2eeJo/EchoFlow?type=whiteboard&t=fsQSIdY2AIh1lTm4-1)
