### ISSUE TITLE
Error while executing HakeFlowDemo.ipynb

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#13]
'TypeError("open_raw() got an unexpected keyword argument \'offload_to_zarr\'")'

The Echopype dependency installed with echoflow is the latest one which does not have a keyword argument 'offload_to_zarr'.

**Comment by Sohambutala** [comment]
Downgrade the echopype version if using it in production mode or remove 'offload_to_zarr=True' from the function call.

**Comment by leewujung** [comment]
I recommend removing `offload_to_zarr=True` from the function call. @lsetiawan will be working on overhauling that capability in the last week of June and the syntax will change, so safer to not use that for now.

**Comment by Sohambutala** [comment]
@leewujung, removed `offload_to_zarr=True` from the function call and it is able to generate the EchoData Object now!

**Comment by leewujung** [comment]
Great!
