### ISSUE TITLE
Dask Code Debug

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#14]
Unable to debug code related to dask and running into the below issue.
Couldn't find a debug adapter descriptor for the debug type 'python' (the extension might have failed to activate)

**Comment by leewujung** [comment]
Hey @lsetiawan could you take a look at this? Thanks!

**Comment by lsetiawan** [comment]
Could you please add a screenshot of the issue or the full code traceback please? Thanks! 🙏🏼

**Comment by Sohambutala** [comment]
Hi Don, 

Please find the below screenshot. 
It doesn't seem like a code issue or dask issue but rather something to do with VS Code itself. I also noticed that sometimes vs code does not pick up file changes unless vs code or the conda environment is not restarted. It might be something to do with caching is what I believe.





![Image](https://github.com/OSOceanAcoustics/echoflow/assets/38330817/1b8c3cc8-fc46-4942-a0ba-2f31754bd246)

**Comment by Sohambutala** [comment]
Closing this issue since we are able to monitor dask workers and see the execution using bokeh.
