### ISSUE TITLE
Echopype Function Input and Output

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#16]
@leewujung , Since the functions are sequentially executed will it be safe to assume that some function's output will always be served as an input to the next function?

For example, we call open_raw and use its output in the combine_echodata function and then use it to compute_Sv. If function arguments will change then it might need some extra handling in the master flow.

**Comment by leewujung** [comment]
> For example, we call open_raw and use its output in the combine_echodata function and then use it to compute_Sv. If function arguments will change then it might need some extra handling in the master flow.

I think for the most common use cases the output of the previous stage would indeed be the input of the next stage. The only exception are input arguments that may come from an EchoData object (e.g., consolidate.add_splitbeam_angle) or from other external functions (e.g., masks generated by echoregions). But yeah the main "pipe" would be the same datasets getting processed going up the stages/levels.

**Comment by Sohambutala** [comment]
Thank you @leewujung for the clarification. I will still try to explore some validation options which can be used once tasks are completed and the first flow is developed.
