### ISSUE TITLE
Mismatched dtypes for variable NMEA_datagram between Zarr store on disk and dataset to append

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#20]
Mismatched dtypes for variable NMEA_datagram between Zarr store on disk and dataset to append. Store has dtype <U74 but dataset to append has dtype <U73.

**Comment by Sohambutala** [comment]
File names that have different dtypes for the NMEA_datagram variable.

Summer2017-D20170627-T174838.raw - 
<xarray.DataArray 'NMEA_datagram' (time1: 30421)>
[30421 values with dtype=<U73]
Coordinates:
  * time1    (time1) datetime64[ns] 2017-06-27T17:48:38.239000064 ... 2017-06...
Attributes:
    long_name:  NMEA datagram


Summer2017-D20170627-T171516.raw - 
<xarray.DataArray 'NMEA_datagram' (time1: 29723)>
[29723 values with dtype=<U74]
Coordinates:
  * time1    (time1) datetime64[ns] 2017-06-27T17:15:16.153999872 ... 2017-06...
Attributes:
    long_name:  NMEA datagram

**Comment by leewujung** [comment]
Are you using echopype v0.7.1? If so, could you try the latest `dev` branch ? there has been major overhaul on `combine_echodata` on that branch from @lsetiawan so let's see if that works out, and if not we can further debug/fix. Thanks!

**Comment by leewujung** [comment]
Also, maybe try files from later part of that cruise, say around mid July. Sometimes in the beginning of the survey people fiddle with instrument settings to make sure everything works fine, so there may be some irregularities that don't usually come up for the initial files. Though of course it is a good thing that you found out about this problem!

**Comment by Sohambutala** [comment]
Thank you @leewujung, it is working with the dev branch!

**Comment by leewujung** [comment]
Great!
