### ISSUE TITLE
Update credential block configuration to read from a file

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echoflow#27]
## Overview

After some discussion over zoom. There's now an agreement that user should setup their credentials to a credential file using the ini format, and that the program should read from that file and create blocks when it doesn't exists. This functionality can leverage the python built-in [`configparser`](https://docs.python.org/3.9/library/configparser.html) library to read these files

## INI Specification

```ini
[DEFAULT] # default section, shouldn't go into a block
provider = aws # default provider

[my-aws-block1] # section header, which is the unique block name as well
# This block will assume the default provider of aws, so should require 'aws_key' and 'aws_secret'
# else put default of None!
aws_key = SOMEAWSKEY
aws_secret = MY$up3rSecretK33Y

[my-azure-block1]
# This block will need to check for 'connection_string' if azure
provider = "azure" # will trump the default provider
connection_string = "az://blah@blah:blah"
```

## Behavior

1. The initial config should look and read from a file called `credentials.ini` in `~/.echoflow/` directory
2. It will go through the sections in ini file and create the appropriate blocks for it
3. If a user rotates a key, they should create a new block by adding a section in the ini and run the configuration step again, otherwise a user can simply go to the Prefect UI and update the block values there

## Expected function

- `echoflow_config`: A function to configure the credentials by reading from a file as described above
  - `sync`: A `bool` argument to `echoflow_config`. This will read the latest values from the existing blocks within prefect and update the local credential files for the respective sections... additionally, for any new sections, new blocks will be created.

**Comment by lsetiawan** [comment]
I've written up what we discussed above, let me know if you have any question. I did add a little new thought I had after the call about having a `sync` flag.

**Comment by Sohambutala** [comment]
The given requirement has been distilled into two actionable commands. Additionally, comprehensive [Blocks](https://github.com/OSOceanAcoustics/echoflow/blob/dev/docs/configuration/blocks.md) documentation has been developed to provide a detailed explanation and step-by-step instructions.

bash

```bash
# Initializes the echoflow environment, Rule Engine, and generates an empty credentials.ini file under ~/.echoflow
echoflow init

# Loads credentials from the ~/.echoflow/credentials.ini file into the Prefect account (local or cloud, based on Prefect profile configuration)
echoflow load-credentials

# Executes the same functionality as the command above, but first synchronizes all blocks from the Prefect account into ~/.echoflow/credentials.ini before loading
echoflow load-credentials --sync
```
