### ISSUE TITLE
Change `.raw` and raw-converted `.zarr` files directory structure

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoflow#30]
Currently with the `echoflow_open_raw`:
- the raw-converted `.zarr` files are grouped under the `{working_directory}/echoflow_open_raw/{transect_name}` (i.e. one folder per "transect", or subgroup txt files)
- the `.raw` files are downloaded and saved to `{working_directory}/echoflow_open_raw/{transect_name}_raw`

We would like to change this to be such that the `.raw` and raw-converted `.zarr` files live in the following directory structure:
- `{working_directory}/echoflow_open_raw/{year}`: this contains the raw-converted `.zarr` files
- `{working_directory}/echoflow_open_raw/{year}_raw`: this contains the `.raw` files
  - we will move these files somewhere else later

**Comment by leewujung** [comment]
Right now for multiple "transect" one can pass in a zip file that contains multiple transect (subgroup) txt files. But we need to change the output directory structure behavior.

**Comment by Sohambutala** [comment]
Closed in #45
