### ISSUE TITLE
Desired output directories from `echoflow_open_raw`

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoflow#31]
The flow `echoflow_open_raw` will generate the following directories:
- in `datastore.yml` we add an argument to specify where the `.raw` files are saved to
- the raw-converted `zarr` files will be saved to `{working_directory}/{flow_name}/{subgroup_txt_filename}` (i.e. 1 folder per subgroup txt file)
  - `flow_name` default is `echoflow_open_raw`

When multiple subgroup txt files are in the input, they will be passed as a zip file.

#30 is a temporary patch.

**Comment by Sohambutala** [comment]
Closed in #45
